version: '3'

services:
  db-container:
    image: shinobi881/getmusiclive-db-container:latest
    ports:
      - 6000:5432
  
  db-middleware:
    image: shinobi881/getmusiclive-database:latest
    build: ./
    volumes: 
      - ./:/usr/src/app
    links:
      - db-container
    depends_on:
      - db-container
    command: ["./wait-for-it.sh", "db-container:5432", "--", "npm run serve"]
    
  getmusiclive-server:
    image: shinobi881/getmusiclive-server:latest
    ports:
      - 5005:80 # must map server port to 80
    links:
      - db-middleware
    depends_on:
      - db-middleware

  getmusiclive-client:
    image: shinobi881/getmusiclive-client:latest
    ports: 
      - 80:80
    links:
      - getmusiclive-server
    depends_on:
      - getmusiclive-server

# --------------------------- #      
# version: '3'
# 
# services:
#   db-container:
#     image: shinobi881/getmusiclive-db-container:latest
#     ports:
#       - 6000:5432
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready"]
#       interval: 30s
#       timeout: 30s
#       retries: 3
#   
#   db-middleware:
#     # image: shinobi881/getmusiclive-database:latest
#     build: ./
#     volumes: 
#       - ./:/usr/src/app
#     ports:
#       - 5010:80
#     links:
#       - db-container
#     depends_on:
#       - db-container
#     
#     command: ["npm", "run", "insertEbData"]
#     
#   getmusiclive-server:
#     image: shinobi881/getmusiclive-server:latest
#     ports:
#       - 5005:80 # must map server port to 80
#     links:
#       - db-middleware
#     depends_on:
#       - db-middleware
# 
#   getmusiclive-client:
#     image: shinobi881/getmusiclive-client:latest
#     ports: 
#       - 5006:5001
#     links:
#       - getmusiclive-server
#     depends_on:
#       - getmusiclive-server
# 
